### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by JasonWeise** [mattkrick/meatier#10]
Hi

I love the idea of your project and am looking to move away from Meteor for my next project so have cloned your repo and npm installed...etc... and have tried to npm start and am receiving the following error (it just keeps recurring in a never ending loop).

````
Origin: Worker (PID 10018)
   [Error] Error: Cannot find module '../../serverBuild/app'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (createSSR.js:17:34)
    at Module._compile (module.js:399:26)
    at loader (/Users/jasonweise/git/meatier/node_modules/babel-register/lib/node.js:130:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/jasonweise/git/meatier/node_modules/babel-register/lib/node.js:140:7)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
1450327170035 - Worker 0 exited - Exit code: 0
````

One thing of note is I had to revert to webpack v1.12.9 in the package.json for npm install to even finish without an error.

Environment..
Node: 5.2
OS: OSX El Capitan

Don't seem to have any dramas with any other frameworks I am evaluating so I figure it is something in your current version considering it is so young.

Any ideas on the above .. thanks in advance.

**Comment by mattkrick** [comment]
Thanks for the heads up! I just added in SSR and that broke a thing or 2. Give me 5 mins & I'll push out a new working copy

**Comment by JasonWeise** [comment]
You are a champion... really looking forward to evaluating this piece of awesomeness... :)

**Comment by mattkrick** [comment]
ugh, i forgot how long npm 3 takes to install stuff... should be good to go thought, feel free to close the issue if the new version is working (also updated the readme, the new server-side editing is probably the coolest feature ever).

**Comment by mattkrick** [comment]
Oh, also webpack 2 is required, otherwise `System.import` is gonna throw a bunch of errors.
Feel free to ignore the peerDep errors that npm throws, those will go away when v2 exits beta.

**Comment by JasonWeise** [comment]
Sadly still an issue. Completely recloned the repo and on first npm install I get the following warnings and error in the log: (webpack@2.0.1-beta also installed as global "just to be sure")

````
.
.
+-- UNMET PEER DEPENDENCY webpack@2.0.1-beta
.
.

npm WARN EPEERINVALID webpack-dev-middleware@1.4.0 requires a peer of webpack@>=1.0.0 <3 but none was installed.
npm WARN EPEERINVALID babel-loader@6.2.0 requires a peer of webpack@^1.0.0 but none was installed.
npm WARN EPEERINVALID extract-text-webpack-plugin@0.9.1 requires a peer of webpack@^1.9.11 but none was installed.
````

**Comment by JasonWeise** [comment]
Scratch that... derp moment... still had previous webpack installed.. sorry appears to be working now (sorry to do that to you lol)

**Comment by JasonWeise** [comment]
Tested working now. 
Closing.
