### ISSUE TITLE
Learning Resources

### ISSUE THREAD

**Issue by fallenpeace** [mattkrick/meatier#100]
Given the fact, a lot of separate packages are being brought together to make a whole,
Would it make sense to add a learning Resources area to the ReadMe and link to relevant information about certain areas?

**Comment by mattkrick** [comment]
Duplicate of #22 #34
I think if someone takes the time to read through each technology on its own, coupled with a decent background in building secure & performant apps, then it's pretty easy to understand how they all fit together.
