### ISSUE TITLE
Production mode not working

### ISSUE THREAD

**Issue by JasonWeise** [mattkrick/meatier#11]
Am testing this beast out and development mode works (npm start) but if testing in production mode (npm run prod) I receive the following error:

````
ReferenceError: System is not defined
    at createSSR (createSSR.js:24:24)
    at Layer.handle [as handle_request] (/Users/jasonweise/git/meatier/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/jasonweise/git/meatier/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/jasonweise/git/meatier/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/jasonweise/git/meatier/node_modules/express/lib/router/layer.js:95:5)
    at /Users/jasonweise/git/meatier/node_modules/express/lib/router/index.js:277:22
    at param (/Users/jasonweise/git/meatier/node_modules/express/lib/router/index.js:349:14)
    at param (/Users/jasonweise/git/meatier/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/Users/jasonweise/git/meatier/node_modules/express/lib/router/index.js:410:3)
    at next (/Users/jasonweise/git/meatier/node_modules/express/lib/router/index.js:271:10)
    at worker.js:43:7
    at Layer.handle [as handle_request] (/Users/jasonweise/git/meatier/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/jasonweise/git/meatier/node_modules/express/lib/router/index.js:312:13)
    at /Users/jasonweise/git/meatier/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/jasonweise/git/meatier/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/jasonweise/git/meatier/node_modules/express/lib/router/index.js:271:10)
````

**Comment by mattkrick** [comment]
well that's annoying...
systemjs still isn't playing nicely with babel 6.
https://github.com/systemjs/systemjs/issues/953
I'll update the readme. basically, you've gotta run a build postinstall, which is kinda annoying...

**Comment by JasonWeise** [comment]
All good, keep up the great work. I have been running through this project and I love what I see so far. I have been looking at a number of frameworks and I really like this so far.

I'll try your new instructions off the readme :+1:

**Comment by mattkrick** [comment]
what other stuff have you been looking at? I couldn't find anything that handled scaling pubsubs, which is why i had to make this thing...

**Comment by JasonWeise** [comment]
I have been looking at everything from the latest versions of Ember and Aurelia with Socket.io with a rethinkdb backend. I had also considered staying with Meteor as I have developed 3 in production apps with it including one with React and Code Splitting with FlowRouter but I came across your post on the Meteor forum today and thought... ohhh this is worth a look :)

**Comment by JasonWeise** [comment]
possibly off topic, I followed your new Readme inclusion and production now runs... but it is basically the same size on initial page load as development.. dev=2.6MB prod=2.5MB. That is with the Vanilla version straight off your repo so I haven't looked into it yet but I thought... ouch.. a bit heavy on production.

**Comment by mattkrick** [comment]
Agreed! I haven't had time to focus on size yet. I know Joi is ridiculously huge https://github.com/hapijs/joi/issues/528

To be honest, I haven't explored it at all. Know of any good tools that can show a nice piechart breakdown or something?

**Comment by JasonWeise** [comment]
Not really, I have only ever "optimised" adhoc with Meteor and Webpack. I have managed to get initial landing page in production to around 300KB with all other routes / components loading on demand with code splitting with Flow Router. As some of our apps are used over slow wifi / 3G links and the main stakeholders have always emphasised importance on the "initial load" it's been a tricky road.. 
I am excited about your platform though so I'd love to see initial pages loads getting trimmed up.
I'm going to see if I can come up with something though JOI is quite heavy as you have said.

**Comment by mattkrick** [comment]
good deal, on that issue I mentioned there's a couple guys who forked joi for the client & got it down to 45kB. Also you can play with the bundles since joi isn't used on the landing page. 

I noticed `build/app.js` still has comments & junk, even after I included uglify in the build. The server-rendered bundle is fully minimized & is about 800kB. Not sure why...

**Comment by mattkrick** [comment]
using devtool: eval causes the whole file to become an eval. who'dve guessed....
ah well, so 800kB is the starting size, react is 136kB, so i'm betting it'd be pretty easy to hit < 300kB without too much tweaking.

**Comment by JasonWeise** [comment]
Good find, I have finished work now (I'm in Australia so go home time). I will try to see where some more improvements can be made when I get home (unless you get it to ~300KB by then) - 300KB is the sweet spot for me so anything around there and I think that'd be great.

**Comment by mattkrick** [comment]
closing this, for production size, see #13
