### ISSUE TITLE
No way to set doctype - older browsers do not handle this well

### ISSUE THREAD

**Issue by patrickleet** [mattkrick/meatier#126]
Using Html.js to generate the initial HTML document, there is no way that I can find to insert a doctype. Older browsers really freak out about this.

First thought was to do something like the answer from this:
http://stackoverflow.com/questions/30626410/server-side-rendering-with-react-react-router-and-express
but not sure how to do that with streaming interface in createSSR.js and this didn't work:

```
const htmlStream = '<!DOCTYPE html>' + renderToStaticMarkup(<Html title="Meatier"
                                                store={store}
                                                assets={assets}
                                                renderProps={renderProps} />);
```

Looks like others have used handlebars to solve - but that seems like too much: https://github.com/jesstelford/react-isomorphic-boilerplate

**Comment by mattkrick** [comment]
I imagine just about everything breaks with anything older than IE8 or 9 & fully believe that folks won't upgrade their browsers unless we give them a reason to & if we continue to sink budget into legacy stuff, we won't embrace the sweet new tech like serviceWorkers & webWorkers. 

But stepping off my soapbox, you're trying to concat a string to a Buffer, which ain't gonna fly. I'm sure stackoverflow has a reasonable simple solution about how to do this, or maybe even the dom-stream package, but I haven't dug into it. If you figure it out it'd make a good PR! :smile:
