### ISSUE TITLE
authToken should be passed to graphql via contextValue

### ISSUE THREAD

**Issue by wenzowski** [mattkrick/meatier#130]
from https://github.com/graphql/graphql-js/commit/d7cc6f9aed462588291bc821238650c98ad53580
> **[RFC] Add explicit context arg to graphql execution**
> This *BREAKING* change introduces a new argument to the GraphQL execution API which is presented to resolution functions: `context`.
> 
> This solves a long-standing point of confusion about the correct way to represent authentication or a "viewer context" in which a query is executed.
> 
> Previously, we suggested that the `rootValue` contain any authentication tokens, however this led to awkward code:
> 
> ```
> resolve: (val, args, { rootValue: { authToken } }) { ... }
> ```
> 
> Which can now be written as:
> 
> ```
> resolve: (val, args, authToken) { ... }
> ```
> 
> The `info` object is still created and provided to resolution functions, and the `rootValue` is still provided within it, however it is now the *fourth* argument rather than the *third*.

I've [built](https://github.com/wenzowski/graphql-js/archive/v0.4.19-alpha0.tar.gz) current [graphql/graphql-js#master](https://github.com/graphql/graphql-js/commit/39744381d5173795d3b245dcb5d86e78bb3638fe) to help get this integrated:
`https://github.com/wenzowski/graphql-js/archive/v0.4.19-alpha0.tar.gz`

Judging by [the new signature](https://github.com/graphql/graphql-js/blob/d7cc6f9aed462588291bc821238650c98ad53580/src/graphql.js#L43) this means separating the `authToken` from the other `rootVals` like so:

```diff
- const result = await graphql(Schema, query, {authToken, ...rootVals}, variables);
+ const result = await graphql(Schema, query, rootVals, authToken, variables);
```

and updating `resolve` functions like so:

```diff
- async resolve(source, args, {rootValue: {authToken}}) {
+ async resolve(source, args, authToken, {rootValue}) {
```

**Comment by mattkrick** [comment]
good eye. personally, it's kind of a bummer since i prefer fewer, deeper args over more, shallow ones, but i guess i'm in the minority. will update this on the next version bump. thanks!

**Comment by wenzowski** [comment]
Most of the time, I'd agree with you but I think this may pave the way to simplifying some of the complex [flow](http://flowtype.org/) types they have declared in there.

**Comment by mattkrick** [comment]
yeah, guess it makes sense. but change is hard, especially with lots of args :)
