### ISSUE TITLE
Error: nData server at socket path 

### ISSUE THREAD

**Issue by puruzio** [mattkrick/meatier#18]
Below is the error message right after the installation when I run npm start. Any idea why this happens?

> meatier@0.5.0 start /Users/puruzio/_dev/meteor/meatier/meatier
> NODE_ENV=development node ./src/server/server.babel.js

   [Busy] Launching SocketCluster
/Users/puruzio/_dev/meteor/meatier/meatier/src/server/init.js:3
    only(filename) {
        ^
SyntaxError: Unexpected token (
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/puruzio/_dev/meteor/meatier/meatier/node_modules/socketcluster/node_modules/iocluster/node_modules/ndata/server.js:20:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
1450568376974 - Origin: IOCluster
   [Error] Error: nData server at socket path /var/folders/sx/sth4f7vn5sq0w0mqtpxx1th80000gn/T//socketcluster/Meatier_e1839c24b0/b0 exited
    at EventEmitter.<anonymous> (/Users/puruzio/_dev/meteor/meatier/meatier/node_modules/socketcluster/node_modules/iocluster/index.js:353:28)
    at EventEmitter.emit (events.js:110:17)
    at ChildProcess.<anonymous> (/Users/puruzio/_dev/meteor/meatier/meatier/node_modules/socketcluster/node_modules/iocluster/node_modules/ndata/index.js:55:10)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
/Users/puruzio/_dev/meteor/meatier/meatier/src/server/init.js:3

**Comment by mattkrick** [comment]
i'm breaking a bunch of stuff right now, but that error has nothing to do with the stuff I'm breaking....
that error is caused by not recognizing es6 method syntax. you sure you got babel6 & webpack2 installed?

**Comment by puruzio** [comment]
Yes I do have them installed.

Jasons-MacBook-Pro:meatier puruzio$ sudo npm install --g babel
Password:
/usr/local/bin/babel -> /usr/local/lib/node_modules/babel/cli.js
/usr/local/bin/babel-external-helpers -> /usr/local/lib/node_modules/babel/cli.js
/usr/local/bin/babel-node -> /usr/local/lib/node_modules/babel/cli.js
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npmconf requires uid-number@'0.0.5' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/uid-number,
npm WARN unmet dependency which is version 0.0.6
babel@6.3.13 /usr/local/lib/node_modules/babel
Jasons-MacBook-Pro:meatier puruzio$ sudo npm install --g webpack
|
> fsevents@1.0.6 install /usr/local/lib/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/usr/local/lib/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v14-darwin-x64/fse.node" is installed via remote
/usr/local/bin/webpack -> /usr/local/lib/node_modules/webpack/bin/webpack.js
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npmconf requires uid-number@'0.0.5' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/uid-number,
npm WARN unmet dependency which is version 0.0.6
webpack@1.12.9 /usr/local/lib/node_modules/webpack
├── interpret@0.6.6
├── tapable@0.1.10
├── clone@1.0.2
├── supports-color@3.1.2 (has-flag@1.0.0)
├── async@1.5.0
├── enhanced-resolve@0.9.1 (graceful-fs@4.1.2, memory-fs@0.2.0)
├── esprima@2.7.1
├── mkdirp@0.5.1 (minimist@0.0.8)
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
├── memory-fs@0.3.0 (errno@0.1.4, readable-stream@2.0.5)
├── webpack-core@0.6.8 (source-list-map@0.1.5, source-map@0.4.4)
├── loader-utils@0.2.12 (big.js@3.1.3, json5@0.4.0)
├── uglify-js@2.6.1 (uglify-to-browserify@1.0.2, async@0.2.10, source-map@0.5.3, yargs@3.10.0)
├── node-libs-browser@0.5.3 (https-browserify@0.0.0, tty-browserify@0.0.0, constants-browserify@0.0.1, path-browserify@0.0.0, os-browserify@0.1.2, string_decoder@0.10.31, process@0.11.2, punycode@1.4.0, assert@1.3.0, querystring-es3@0.2.1, timers-browserify@1.4.2, domain-browser@1.1.7, stream-browserify@1.0.0, events@1.1.0, console-browserify@1.1.0, vm-browserify@0.0.4, util@0.10.3, http-browserify@1.7.0, readable-stream@1.1.13, url@0.10.3, buffer@3.5.5, browserify-zlib@0.1.4, crypto-browserify@3.2.8)
└── watchpack@0.2.9 (graceful-fs@4.1.2, async@0.9.2, chokidar@1.4.1)

**Comment by mattkrick** [comment]
> webpack@1.12.9 /usr/local/lib/node_modules/webpack

you'll need to `sudo npm -i -g webpack@2.0.1-beta`

**Comment by puruzio** [comment]
It's working! Thanks.

It still complains about unmet peer dependency, but things appear to work anyway.

npm WARN EPEERINVALID extract-text-webpack-plugin@0.9.1 requires a peer of webpack@^1.9.11 but none was installed.
npm WARN EPEERINVALID webpack-dev-middleware@1.4.0 requires a peer of webpack@>=1.0.0 <3 but none was installed.
npm WARN EPEERINVALID babel-loader@6.2.0 requires a peer of webpack@^1.0.0 but none was installed.
npm WARN EPEERINVALID stats-webpack-plugin@0.2.2 requires a peer of webpack@^1.0 but none was installed.

**Comment by mattkrick** [comment]
yeah, it'll do that until webpack2 leaves beta. 
still can't believe that error was caused by webpack, that's confusing...

**Comment by puruzio** [comment]
You are  right.  I had the wrong node version also.  After upgrading to Node 5 and reinstalling all the packages fixed my issue. This repo looks really promising. Thank you for sharing!
