### ISSUE TITLE
Failed propType: Required prop `children` was not specified in `AppContainer`.

### ISSUE THREAD

**Issue by puruzio** [mattkrick/meatier#21]
Strangely, these errors happen only on Safari, but not on Chrome. As a result, the login form doesn't appear on Safari. Any clue?

[Error] Warning: Failed propType: Required prop `children` was not specified in `AppContainer`. Check the render method of `TokenizedComp`.
	warning
	checkPropTypes
	validatePropTypes
	createElement
	render
	tryRender
	_renderValidatedComponentWithoutOwnerOrContext
	_renderValidatedComponent
	ReactCompositeComponent__renderValidatedComponent
	_updateRenderedComponent
	_performComponentUpdate
	updateComponent
	ReactCompositeComponent_updateComponent
	receiveComponent
	receiveComponent
	_updateRenderedComponent
	_performComponentUpdate
	updateComponent
	ReactCompositeComponent_updateComponent
	receiveComponent
	receiveComponent
	_updateRenderedComponent
	_performComponentUpdate
	updateComponent
	ReactCompositeComponent_updateComponent
	receiveComponent
	receiveComponent
	_updateRenderedComponent
	_performComponentUpdate
	updateComponent
	ReactCompositeComponent_updateComponent
	performUpdateIfNecessary
	performUpdateIfNecessary
	runBatchedUpdates
	perform
	perform
	perform
	flushBatchedUpdates
	ReactUpdates_flushBatchedUpdates
	(anonymous function)
	closeAll
	perform
	batchedUpdates
	enqueueUpdate
	enqueueUpdate
	enqueueSetState
	setState
	(anonymous function)
	(anonymous function)
	(anonymous function)
	done
	(anonymous function)
	getComponentsForRoute
	(anonymous function)
	(anonymous function)
	forEach
	mapAsync
	getComponents
	(anonymous function)
	done
	next
	(anonymous function)
	(anonymous function)
	(anonymous function)
	(anonymous function)
	next
	loopAsync
	runEnterHooks
	finishMatch
	(anonymous function)
	done
	(anonymous function)
	(anonymous function)
	done
	(anonymous function)
	(anonymous function)
	(anonymous function)
	_callee$
	tryCatch
	invoke
	(anonymous function)
	step
	(anonymous function)
	promiseReactionJob
[Error] Warning: Failed propType: Required prop `children` was not specified in `App`. Check the render method of `AppContainer`.
	warning
	checkPropTypes
	validatePropTypes
	createElement
	render
	_renderValidatedComponentWithoutOwnerOrContext
	_renderValidatedComponent
	ReactCompositeComponent__renderValidatedComponent
	_updateRenderedComponent
	_performComponentUpdate
	updateComponent
	ReactCompositeComponent_updateComponent
	receiveComponent
	receiveComponent
	_updateRenderedComponent
	_performComponentUpdate
	updateComponent
	ReactCompositeComponent_updateComponent
	receiveComponent
	receiveComponent
	_updateRenderedComponent
	_performComponentUpdate
	updateComponent
	ReactCompositeComponent_updateComponent
	receiveComponent
	receiveComponent
	_updateRenderedComponent
	_performComponentUpdate
	updateComponent
	ReactCompositeComponent_updateComponent
	receiveComponent
	receiveComponent
	_updateRenderedComponent
	_performComponentUpdate
	updateComponent
	ReactCompositeComponent_updateComponent
	performUpdateIfNecessary
	performUpdateIfNecessary
	runBatchedUpdates
	perform
	perform
	perform
	flushBatchedUpdates
	ReactUpdates_flushBatchedUpdates
	(anonymous function)
	closeAll
	perform
	batchedUpdates
	enqueueUpdate
	enqueueUpdate
	enqueueSetState
	setState
	(anonymous function)
	(anonymous function)
	(anonymous function)
	done
	(anonymous function)
	getComponentsForRoute
	(anonymous function)
	(anonymous function)
	forEach
	mapAsync
	getComponents
	(anonymous function)
	done
	next
	(anonymous function)
	(anonymous function)
	(anonymous function)
	(anonymous function)
	next
	loopAsync
	runEnterHooks
	finishMatch
	(anonymous function)
	done
	(anonymous function)
	(anonymous function)
	done
	(anonymous function)
	(anonymous function)
	(anonymous function)
	_callee$
	tryCatch
	invoke
	(anonymous function)
	step
	(anonymous function)
	promiseReactionJob

**Comment by mattkrick** [comment]
may be linked to #6. Try the solution there or try it out in prod mode & see if that fixes it. agreed, strange that a proptypes error is browser specific... i'll dig into it after vacation
