### ISSUE TITLE
Poor Readme

### ISSUE THREAD

**Issue by n0ne** [mattkrick/meatier#22]
Meteor is awesome, but his future is not clear
It'll be great, if you will write something like docs.meteor.com or guide.meteor.com
Thank you

**Comment by praneybehl** [comment]
Some more documentation will really help people who are not "yet" super cool ;)

**Comment by stereobooster** [comment]
`Vagrantfile` as quick start would be handy

**Comment by mattkrick** [comment]
PRs welcomed :wink: 
I'm not really writing something to compete with Meteor...heck, I didn't really write anything at all! I just picked out some packages that fit nicely together to solve the problem of creating a SaaS. What are you wanting to do? I don't have any "Meatier" proprietary methods, so if you want to do verification, you can look at Joi's readme. If you want info on sockets, you can read up on socketCluster, etc. Let me know what's confusing & i'll mark out some time for a blog post or 2.

**Comment by mattkrick** [comment]
Closing as this is pretty generic. If there's a specific topic, feel free to open a separate issue or make a PR.
