### ISSUE TITLE
First time browsing to localhost after npm start

### ISSUE THREAD

**Issue by dec0y** [mattkrick/meatier#25]
Tried this every which way I know and I keep receiving this error when I browse to localhost:3000 after following the steps. I am sure it is something stupid, just not sure what exactly. This is showing in the second terminal window where I used "npm start"

ERROR in Entry module not found: Error: Cannot resolve module 'react-json-tree/lib/index.js' in /Users/thom/Desktop/meatier/src

ERROR in Entry module not found: Error: Cannot resolve module 'react-dock/lib/index.js' in /Users/thom/Desktop/meatier/src

**Comment by mattkrick** [comment]
im guessing you didn't run the install or the build, since webpack is probably erroring in the prefetch stage. `npm run install && npm run build`. reopen if this doesn't solve it.

**Comment by dec0y** [comment]
I did run the install and build(even with sudo just in case). Will try your suggestion again and reopen if need be.

**Comment by metstrike** [comment]
Fantastic project - thank you for putting it together.

I am able to run ```npm run quickstart``` but ```npm start``` still gives me:

```
ERROR in Entry module not found: Error: Cannot resolve module 'react-json-tree/lib/index.js' in /u01/workspace/meatier/src

ERROR in Entry module not found: Error: Cannot resolve module 'react-dock/lib/index.js' in /u01/workspace/meatier/src
```

The errors show after I ran ```npm install``` which gives me some warnings:

```
npm WARN optional Skipping failed optional dependency /piping/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.7
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.7
npm WARN babel-loader@6.2.1 requires a peer of webpack@^1.0.0 but none was installed.
npm WARN codemirror-graphql@0.2.2 requires a peer of graphql@^0.4.16 but none was installed.
npm WARN extract-text-webpack-plugin@1.0.1 requires a peer of webpack@^1.9.11 but none was installed.
npm WARN react-addons-create-fragment@0.14.7 requires a peer of react@^0.14.7 but none was installed.
npm WARN react-addons-pure-render-mixin@0.14.7 requires a peer of react@^0.14.7 but none was installed.
npm WARN react-addons-transition-group@0.14.7 requires a peer of react@^0.14.7 but none was installed.
npm WARN react-addons-update@0.14.7 requires a peer of react@^0.14.7 but none was installed.
npm WARN stats-webpack-plugin@0.3.0 requires a peer of webpack@^1.0 but none was installed.
npm WARN webpack-dev-middleware@1.4.0 requires a peer of webpack@>=1.0.0 <3 but none was installed.
```

And ```npm run build``` seems ok:

```[1] npm run build:server exited with code 0
.
.
.
[0] Hash: a40ba74e732fe4779e71
[0] Version: webpack 2.0.2-beta
[0] Time: 22770ms
[0]                                Asset     Size  Chunks             Chunk Names
[0] 37681ed619fcde1be52da659ee7288ff.jpg   243 kB          [emitted]  
[0]            0_ceca9d4c2deabd7cdd3e.js  39.6 kB    0, 4  [emitted]  
[0]            1_b13ee5ff0eac17e275c1.js    40 kB    1, 4  [emitted]  
[0]            2_964177b408b86e142272.js   218 kB    2, 4  [emitted]  
[0]            3_6236f73e42a75199f35f.js   623 kB    3, 4  [emitted]  
[0]     manifest_f36dacb196119413bc3f.js  2.62 kB       4  [emitted]  manifest
[0]          app_7ada064b7a3dbb62de36.js   634 kB    5, 4  [emitted]  app
[0]       vendor_785ddb90e03d8f5064cc.js   749 kB    6, 4  [emitted]  vendor
[0]    [2] multi app 40 bytes {5} [built]
[0]    [3] multi vendor 52 bytes {6} [built]
[0]     + 1194 hidden modules
[0] npm run build:client exited with code 0
```

**Comment by Bartekus** [comment]
FYI, you should never install any package manager with sudo, this especially applies to npm.
Please look into fixing the npm permissions by following this official guide: https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by Bartekus** [comment]
@metstrike are you running linux by any chance? The reason why I'm asking is that I usually see `npm WARN optional Skipping failed optional dependency /chokidar/fsevents:` primarily on linux and the easiest way to deal with it at the moment is to downgrade to npm ^2.x.x

**Comment by metstrike** [comment]
@Bartekus thank you for your advice, I am using CentOS 7 and my npm version in 3.6.0. 

I followed the instructions from https://nodejs.org/en/download/package-manager/ that recommends to install everything as **root**:

```
Enterprise Linux and Fedora
Including Red Hat® Enterprise Linux® / RHEL, CentOS and Fedora.

Run as root on RHEL, CentOS or Fedora, for Node.js v4 LTS Argon:

curl --silent --location https://rpm.nodesource.com/setup_5.x | bash -

Then install, as root:

yum -y install nodejs
```

**Comment by mattkrick** [comment]
Thnx for controlling this @bartekus. If there's any issues let me know, it
should be touch n go.

**Comment by metstrike** [comment]
@mattkrick what is the recommended vanilla environment for meatier?
Host OS (not linux?) and versions of node and npm?

**Comment by Bartekus** [comment]
I would say that at the moment I only gave a proper consideration to ubuntu, but that is not to say that other *nixes wont be possible. So at the moment I would say try to grab the build on the araphel brunch and execute it thru azk.io, it will allow you to operate and deploy meatier on *nix

**Comment by mattkrick** [comment]
ubuntu has received a lot of love wrt servers lately, my next deploy might even favor ubuntu over debian. There is no hard dependency on node v5, but i'd recommend that + the latest npm3. To compensate for the LOOONG npm3 installs i use local-npm. To switch node versions, eg if you want to play with relay, i recommend n. I should probably write something up on how to be productive in npm land as it's still the wild west out there.

**Comment by metstrike** [comment]
After installing ubuntu 14.04.3 LTS I am able to run ```npm start```. Thanks! It looks like though other flavors of linux like RHEL/CentOS may have a problem.

**Comment by mattkrick** [comment]
Both of those errors you originally mentioned come from redux dev tools, so after moving to a chrome extension it mayvwork itself out. Unfortunately I'm a cheapass and bought a laptop with a 128GB HD, so I can't test on anything but osx :cry:

**Comment by kurtaschliman** [comment]
With a fresh install on OSX of the latest code at e0b9f12, I receive the following errors as well on `npm start` after running `npm install` and `npm run build`. 

```
ERROR in Entry module not found: Error: Cannot resolve module 'react-json-tree/lib/index.js' in /Users/Kurt/Sites/meatier/src

ERROR in Entry module not found: Error: Cannot resolve module 'react-dock/lib/index.js' in /Users/Kurt/Sites/meatier/src
```

Either commenting out the lines in `webpack.config.dev.js` or adding back the redux-devtools packages removes the module resolution issue, but then on `npm start` I'm met with a blank screen and this console error: 

```
Uncaught TypeError: _dispatch is not a function
```

I'm running Node v5.6.0 and NPM v3.6.0 and have webpack 2.0.2-beta installed globally.

**Comment by mattkrick** [comment]
good catch, guess that's what i get for accepting PRs when I can't fully test em :confused: i'll see if i can find some decent internet tomorrow & dig in
