### ISSUE TITLE
How to get in touch?

### ISSUE THREAD

**Issue by themeteorchef** [mattkrick/meatier#30]
Hey, Matt! Trying to find a good way to get in touch but can't find an email address for you. Could you share an email here or shoot me an email personally (ryan.glover@themeteorchef.com)?

**Comment by cryptoquick** [comment]
Very exciting that you're interested in this awesome alternative! @mattkrick -- In line with the spirit of this issue, perhaps a Gitter might be appropriate; I've gotten mixed responses discussing Meteor alternatives in current Meteor groups.

**Comment by mattkrick** [comment]
Good call on the gitter, I'll set it up when I get back from vacation. @themeteorchef email is matt.krick@gmail.com

**Comment by mattkrick** [comment]
all set on the gitter, thanks for waiting!
