### ISSUE TITLE
React Native?

### ISSUE THREAD

**Issue by fungilation** [mattkrick/meatier#38]
Hi, I'm new to React (Native) and Redux. I'm starting an app that requires native components so React Native it is. Just asking here before I dive in, that with meatier's choice of stack, would using React Native instead of React proper a problem?

Thanks for your thoughts.

**Comment by mattkrick** [comment]
Do it up! I haven't taken the time to write a React Native equivalent, but that's definitely the recommended path & the switch to React Native should be fairly painless. If you converted Meatier into React Native that'd be the most amazing PR ever & would be a big help!

**Comment by mattkrick** [comment]
Closing since there's nothing actionable here, if you do write a React Native version I'd love to see it!

**Comment by fungilation** [comment]
There's currently some challenge getting RethinkDB to play nice with RN, but I think it's now mostly resolved: https://github.com/mikemintz/react-rethinkdb/issues/11

**Comment by mattkrick** [comment]
that's not a problem with rethinkDB, rather with react-rethinkdb. If you follow the Meatier stack, you won't have to use that package, but i encourage you to try it out. Personally, wasn't my style. Client-side stuff like that is a nonstarter when you eg need to verified user credentials, need an accurate timestamp, etc.

**Comment by fungilation** [comment]
I see. I'm still deliberating backend choices. I was going to go with Parse until they just [shut it down](http://blog.parse.com/announcements/introducing-parse-server-and-the-database-migration-tool/) (sad).

App I'm working on is very client heavy, so things like Firebase and react-rethinkdb would be my style. Those are the 2 I'm deciding, or meatier obviously if dropping in RN in place of React is relatively pain free...
