### ISSUE TITLE
Front End

### ISSUE THREAD

**Issue by tvld** [mattkrick/meatier#42]
Great stuff and I think you are taking a interesting path. Wondering however why React ? I got the feeling we need something fully ES6/7 and not another propitiatory (.jsx)  format. Thought about Aurelia.io as excellent Front End from the original Angular 1.0 (but not 2.0) Developer. They are fully standard JS compliant.

**Comment by mattkrick** [comment]
Server side rendering, async routing, vdom performance, community activity, financial backing, react native, one-way data flow, and battle tested. Only thing angular 2 has on it is its use of webworkers. Aurelia still has a state thats hard to reason about in medium to large apps. Really, nothing else comes close :smile:
