### ISSUE TITLE
Add oauth login for facebook & google

### ISSUE THREAD

**Issue by mattkrick** [mattkrick/meatier#5]
Logging in with oauth (google/facebook) should return an email address & profile pic. The token & and pic url should be stored in an `accounts` objects nested in the `user` document. Since this is pure JWTs, it may be easier to do this without using passport.js. If someone has experience with oauth & JWTs, let me know!

**Comment by djhi** [comment]
I have used [hello.js](https://adodson.com/hello.js/) before to achieve oauth with popup and jwt authentication on my app. I remember having to implement [oauth-shim](https://www.npmjs.com/package/oauth-shim) to avoid having my oauth credentials on client side. Can't remember the details tough. I thought you'd like to know about this.

**Comment by mattkrick** [comment]
i'll check it out, thanks! yeah, i wasn't a fan of using passport for pure JWTs, seemed like it didn't provide much value.
