### ISSUE TITLE
What about a meatier logo for temporary use?

### ISSUE THREAD

**Issue by loongmxbt** [mattkrick/meatier#53]
![meatier-logo](https://cloud.githubusercontent.com/assets/5986600/12841730/d500562a-cc28-11e5-84d9-90ae6abd5486.png)

Two hamburgers -> meatier
Two burgers -> 2 letter `e`
Symmetry burger position

Seems delicious :-) If you agree, I'll send a PR later.

**Comment by mattkrick** [comment]
haha i love it! it's hard to see that the burgers represent the letter e, but other than that it's really great!

**Comment by loongmxbt** [comment]
#56 PR
