### ISSUE TITLE
Update redux-simple-router

### ISSUE THREAD

**Issue by sompylasar** [mattkrick/meatier#65]
It has recently been deprecated, and the modern version is called https://github.com/reactjs/react-router-redux

**Comment by Bartekus** [comment]
This already been looked after, as we are working on a new release where these changes will be reflected. However, thank you for your observation in that regard.

**Comment by sompylasar** [comment]
:+1: would you mind keeping this issue open until the release is released?

**Comment by Bartekus** [comment]
Ok your changes have been implemented and tested ok on the [Araphel](https://github.com/Araphel/meatier) branch

**Comment by sompylasar** [comment]
@Bartekus left several comments [there](https://github.com/Araphel/meatier/commit/012023ae4b37de953ba4550a3ebd58f0f2735554).

**Comment by Bartekus** [comment]
Indeed, I'll have them resolved momentarily, just gotta grab something to eat, thank you for your help!

**Comment by sompylasar** [comment]
Thanks!
