### ISSUE TITLE
upgrade to the latest webpack 2 version

### ISSUE THREAD

**Issue by mattkrick** [mattkrick/meatier#73]
https://medium.com/modus-create-front-end-development/webpack-2-tree-shaking-configuration-9f1de90f3233#.8eeincywi

**Comment by Bartekus** [comment]
lol, they are using our package it seems Matt, good that we have updated it and like I mentioned, I'm almost done with updates, just gotta test in browser and do a little bit of inspection.

**Comment by mattkrick** [comment]
haha are they? how can you tell?

**Comment by Bartekus** [comment]
`
npm i babel-preset-es2015-native-modules --save-dev
`

https://github.com/Araphel/babel-preset-es2015-native-modules

:D

**Comment by ShaggyDude** [comment]
Nice!

**Comment by mattkrick** [comment]
ohhh *that* package. nice!

**Comment by Bartekus** [comment]
Done on #77

**Comment by Bartekus** [comment]
I'll submit proper pull tomorrow morning, meanwhile if it's a rush there is this: https://github.com/r3stack/r3stack
