### ISSUE TITLE
npm install: unmet peer dependency

### ISSUE THREAD

**Issue by metstrike** [mattkrick/meatier#78]
Environment:
- ubuntu 14.04.3 LTS
- node 5.6.0
- npm 3.6.0

node/npm has been installed according to the official instructions at: https://nodejs.org/en/download/package-manager/

During the meatier installation, the ```npm install``` step finished with bunch of warnings about unmet peer dependencies. Is it something to worry about?

```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.7
npm WARN codemirror-graphql@0.2.2 requires a peer of graphql@^0.4.16 but none was installed.
npm WARN react-addons-transition-group@0.14.7 requires a peer of react@^0.14.7 but none was installed.
npm WARN react-addons-update@0.14.7 requires a peer of react@^0.14.7 but none was installed.
npm WARN react-addons-pure-render-mixin@0.14.7 requires a peer of react@^0.14.7 but none was installed.
npm WARN react-addons-create-fragment@0.14.7 requires a peer of react@^0.14.7 but none was installed.
npm WARN babel-loader@6.2.1 requires a peer of webpack@^1.0.0 but none was installed.
npm WARN extract-text-webpack-plugin@1.0.1 requires a peer of webpack@^1.9.11 but none was installed.
npm WARN webpack-dev-middleware@1.4.0 requires a peer of webpack@>=1.0.0 <3 but none was installed.
npm WARN stats-webpack-plugin@0.3.0 requires a peer of webpack@^1.0 but none was installed.
```

Otherwise the **meatier** installation finished ok, and the basic Kanban demo seems to work in both quickstart and client development mode.

**Comment by Bartekus** [comment]
Nope, fsevents is referring to functions that are part of linux natively hence there is no point installing them as so npm get confused and throws and error, this is at the moment common on npm 3^ but non existent on npm 2^ 

I wouldn't worry about it, everything else will work as it should.
