### ISSUE TITLE
Get serious - Rename the project

### ISSUE THREAD

**Issue by metstrike** [mattkrick/meatier#84]
Matt!

 You started a truly amazing project, you got 1667 stars in 3 months, you got contributors, almost 100 PRs, there is definitely some magic in what you put together and it is getting traction.

Maybe be there is more to it that you have ever imagined, maybe you are changing the way the web applications will be developed going forward. Maybe you are right the platforms are dead a this is the way to go. Maybe you are solving the javascript fatigue, maybe you are sorting out the mess that all web developers are drowning in, whatever, this is your chance to make something big out of it.

You should probably head to San Francisco and start looking for seed investment, setup a startup, hire few good engineers, grow an open source community. Everything is possible!

No matter what you choose to do next, I recommend you change the name of this repository to something showing this is a serious project. The name meatier is definitely funny and made a lot of sense in relation to meteor, but it's time to make a name that is presentable to investors, enterprises, academic institutions, and government organizations.

**Comment by Bartekus** [comment]
We're on it already... but I think you underestimate the power of humor :P
[meatier.io](http://meatier.io/) is great name for transitioning from what was: meteor, what is: meatier... and what will be... :P

We though about that already and have a serious name for serious types like you :P 
R3stack
![r3stack](https://cloud.githubusercontent.com/assets/7887446/13169993/3ef7d9ea-d6a6-11e5-9798-96e443ae4909.png)

Serious yes, but not as playful and zesty as meatier and we try to spark spirit of creation in young people, so it should be funny and not be taken as seriously as morning coffee.

For now we want to attract as much Meteor community as possible for this dream is the dream of all of us. Once everything is perfected it can be boxed in something that can be packed and marketed.

**Comment by metstrike** [comment]
Cool! How about for now you put some stable release to r3stack and continue with rapid development at meatier?

**Comment by Bartekus** [comment]
We'll we need to figure out dev-tools issue and also a solid enough npm lifecycle, since atm it's not bulletproof enough :/

**Comment by mattkrick** [comment]
haha it's not like this stack was built to scale to hundreds of thousands of concurrent connections in a secure production environment
...oh wait :stuck_out_tongue_winking_eye:

**Comment by ncrmro** [comment]
I'm looking at 

[npm-check-updates](https://github.com/tjunnone/npm-check-updates) - lists and upgrades your package.json.

and [shrinkwrap](https://docs.npmjs.com/cli/shrinkwrap) - Lock down dependency versions

any thoughts?

**Comment by Bartekus** [comment]
@ncrmro Nothing can replace diligence and proper test suite; when one creates module or set of modules, the best way to ensure smooth operation is by personally ensuring that each upgrade is managed and overseen by human. There are exceptions to each rule and so it's best to avoid unforeseen consequence is to understand context and implication that arise from it. In absence of full test coverage, a more cumbersome yet very effective way for a developer is to use things such as [NPM Click](http://npm.click) to manually upgrade packages while checking upgrade log to see what was changed and how it can affect the overall build. Once a sufficient test coverage is achieved, services such as http://greenkeeper.io/ can be employed to fully automate the process. So while I'm not advocating for or against your proposition (in fact I'm incorporating these suggestion in order to test their viability), Im always stay conscious of offloading responsibility to thirt-party agents which are incapable of at all times being aware of context and implications. At the moment, semantic versioning is not yet standardized enough to depend solely on numbers in upgrade mechanics so no matter what, a properly supervised and tested technique is necessary to ensure smooth upgrade path.

**Comment by Bartekus** [comment]
@mattkrick lol, give them a hand, and they'll want a whole arm :P
I think people have quite elevated expectation from something that is freely developed and maintained, as it is the case with majority of open software initiatives. On top of it, when it's that easy to get, it is often under-appreciated - giving the right to the saying, easy come, easy go - :( I guess we don't have to look much farther than what's happening with Express to understand the implications of such thinking. But overall, I think we should be happy and cherish everything, no matter how difficult or unappreciated it is :)

**Comment by ncrmro** [comment]
@Bartekus honestly I hope I'm not coming of ungrateful or demanding. I think the project is fantastic. 

The shrinkwrap was more of a suggestion for having a unified set of dependencies release for R3stack. I appreciate the let the user see everything methodology.

I'm just still learning a lot of the stuff looking through the code and how best to contribute back whether documenting issues, making changes or seeing what's in the pipeline. 

I have CI where Circle CI Builds and test a Docker image then Pushes to Dockerhub and triggers a webhook on tutum (hosted on aws) to redeploy if your interested.

**Comment by mattkrick** [comment]
so i don't use shrinkwrap, but i do set to an exact version & use ncu to pick up updates. greenkeeper is another good option, when it gets more stable i'll move to that.

**Comment by faiizow** [comment]
ive actually become too fond of the burger

please consider Burger.js :ok_hand:

**Comment by Bartekus** [comment]
Ok here is the stable, updated r3stack (rebrand of Meatier for the serious folks, but still the same good old Meatier)
It's fully integrated with azk.io so you can just get on with development and if you feel like it, with single command deploy it as well. Cheers!

**Comment by morningrat** [comment]
@Bartekus The only reason I used Meatier was because of its name. I guess I'll quit now.

**Comment by Bartekus** [comment]
Can't please everybody eh ;)

**Comment by metstrike** [comment]
Very nice, r3stack is much more presentable in real business environment. I think you actually can please both crowds, use r3stack for stable releases and continue using meatier for rapid development and experimental new features.

**Comment by mattkrick** [comment]
@metstrike not a bad idea. i'll be back in the world of semi-reliable internet tomorrow & can start hacking on this again. fun times to come!

**Comment by tomByrer** [comment]
> use r3stack for stable releases and continue using meatier for rapid development and experimental new features

I agree nice idea.

**Comment by Bartekus** [comment]
Indeed, as do I!

**Comment by mattkrick** [comment]
I think breaking this into a hacker & stable branch seems the best path forward & we're already kinda headed that direction. Will close for now, feel free to keep the discussion going.
