### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by brw31415** [mattkrick/meatier#88]
==> make install MANDIR=/home/ubuntu/.linuxbrew/Cellar/openssl/1.0.2f/share/man MANSUFFIX=ssl
Error: parent directory is world writable but not sticky
Please report this bug:
    https://github.com/Linuxbrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tmpdir.rb:92:in `mktmpdir'
/home/ubuntu/.linuxbrew/Library/Homebrew/utils/fork.rb:6:in `safe_fork'
/home/ubuntu/.linuxbrew/Library/Homebrew/formula_installer.rb:594:in `build'
/home/ubuntu/.linuxbrew/Library/Homebrew/formula_installer.rb:220:in `install'
/home/ubuntu/.linuxbrew/Library/Homebrew/formula_installer.rb:453:in `install_dependency'
/home/ubuntu/.linuxbrew/Library/Homebrew/formula_installer.rb:402:in `block in install_dependencies'
/home/ubuntu/.linuxbrew/Library/Homebrew/formula_installer.rb:402:in `each'
/home/ubuntu/.linuxbrew/Library/Homebrew/formula_installer.rb:402:in `install_dependencies'
/home/ubuntu/.linuxbrew/Library/Homebrew/formula_installer.rb:177:in `install'
/home/ubuntu/.linuxbrew/Library/Homebrew/cmd/install.rb:215:in `install_formula'
/home/ubuntu/.linuxbrew/Library/Homebrew/cmd/install.rb:94:in `block in install'
/home/ubuntu/.linuxbrew/Library/Homebrew/cmd/install.rb:94:in `each'
/home/ubuntu/.linuxbrew/Library/Homebrew/cmd/install.rb:94:in `install'
/home/ubuntu/.linuxbrew/Library/brew.rb:83:in `<main>'
brw314:~/workspace $ sudo brew install rethinkdb                                                               
Error: Cowardly refusing to 'sudo brew install'
You can use brew with sudo, but only if the brew executable is owned by root.
However, this is both not recommended and completely unsupported so do so at
your own risk.

**Comment by Bartekus** [comment]
uhhh ohhh... just use the azk.io to launch you rethinkdb or use a docker rethinkdb... much better and easier way to work with it

**Comment by brw31415** [comment]
i'm having problems with that, can i just run mongo and will it find it?

**Comment by Bartekus** [comment]
ughh mongo... you're on your own there, I'm not a fan of corporate bs...

**Comment by mattkrick** [comment]
why are you using sudo with homebrew? that's a big nono.... just brew update & then install rethinkdb & it should go off without a hitch

**Comment by brw31415** [comment]
i honestly know nothing about brew, but i'll try again later

**Comment by patrickleet** [comment]
@brw31415 may want to try the command ```brew doctor``` to fix your homebrew setup

**Comment by wmertens** [comment]
@brw31415 Not sure in how far it's broken, but you might be able to do `sudo chown -R $USER ~/.linuxbrew /usr/local; sudo chmod -R og-w ~/.linuxbrew /usr/local`, which will change those directories to be owned by you and only writeable by you.

Really confused about you using Homebrew (OS X) and it going to something Linuxy and your username being Ubuntu though.

**Comment by mattkrick** [comment]
Closing as I think this is more of a brew issue than meatier, feel free to continue troubleshooting here if needed
