### ISSUE TITLE
npm install failing

### ISSUE THREAD

**Issue by ciwolsey** [mattkrick/meatier#9]
When running npm install I get the following output:

https://gist.github.com/ciwolsey/fc9229b75905cd139595

Node 5.2.0 / Arch LInux

**Comment by mattkrick** [comment]
ACK! thanks for letting me know, i forgot to delete a postinstall script i was debugging. Will update in the next couple minutes. In the meantime, remove the `postinstall` from the `package.json`

**Comment by mattkrick** [comment]
closing, should be fixed now, let me know if it isn't.
