### ISSUE TITLE
Commit from 2016-02-18 18:29:46 - the SIGN UP functionality is broken

### ISSUE THREAD

**Issue by metstrike** [mattkrick/meatier#90]
When I check out the commit from 2016-02-18 18:29:46 the SIGN UP functionality is broken.
When I go back to the commit from 2016-02-13 07:08:03 it works.

**Comment by wmertens** [comment]
That's probably due to the Redux store being broken, try instead with the pull from #85. You'll need to npm install.

**Comment by mattkrick** [comment]
#85 accepted (Thanks @wmertens).
@metstrike let me know if that fixed it

**Comment by metstrike** [comment]
Yes, #85 has fixed it, the current master works as expected, closing this issue.
